# Site settings
title: Madeeha Ghori
header-img: "/images/home-bg.jpg"
email: madeeha.ghori@berkeley.edu
tagline: "the personal website of madeeha ghori"
url: "https://madcode.github.io"
github_username:  madCode
linkedin: https://www.linkedin.com/pub/madeeha-ghori/40/6b8/65b
hackster_username: madcode

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
plugins: ["jekyll-paginate"]
paginate: 5
paginate_path: "page:num"
include: [".well-known"]
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]